version: '3.8'
volumes:
  pg_data:
services:
  db:
    image: postgres:16.2-alpine
    env_file:
      - backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'