# Generated by Django 4.2.11 on 2024-04-09 20:37

import django.core.validators
import django.db.models.deletion
import workout.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkoutProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("gain", "Набор"),
                            ("loss", "Сушка"),
                            ("maintain", "Поддержание"),
                        ],
                        max_length=10,
                        verbose_name="Цель",
                    ),
                ),
            ],
            options={
                "verbose_name": "программа тренировок",
                "verbose_name_plural": "программы тренировок",
                "unique_together": {("gender", "goal")},
            },
        ),
        migrations.CreateModel(
            name="WorkoutType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="workout_icons/",
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип тренировки",
                "verbose_name_plural": "типы тренировок",
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="workout_videos/",
                        validators=[workout.validators.validate_video_extension],
                        verbose_name="Видео",
                    ),
                ),
                (
                    "workout_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="workout.workouttype",
                        verbose_name="Тип тренировки",
                    ),
                ),
            ],
            options={
                "verbose_name": "тренировка",
                "verbose_name_plural": "тренировки",
            },
        ),
        migrations.CreateModel(
            name="WorkoutProgramDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "repetitions",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Количество повторений",
                    ),
                ),
                (
                    "sets",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Количество подходов",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Продолжительность (мин.)"
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.workout",
                        verbose_name="Тренировка",
                    ),
                ),
                (
                    "workout_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_details",
                        to="workout.workoutprogram",
                        verbose_name="Программа тренировок",
                    ),
                ),
            ],
            options={
                "verbose_name": "элемент программы тренировок",
                "verbose_name_plural": "элементы программы тренировок",
                "ordering": ["order"],
                "unique_together": {("workout_program", "workout", "order")},
            },
        ),
    ]
