# Generated by Django 4.2.11 on 2024-04-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutprogram',
            old_name='goal',
            new_name='aim',
        ),
        migrations.RenameField(
            model_name='workoutprogram',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AlterUniqueTogether(
            name='workoutprogram',
            unique_together={('sex', 'aim')},
        ),
    ]
