# Generated by Django 4.2.11 on 2024-04-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workouttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workouttype',
            name='updated_at',
        ),
    ]
