# Generated by Django 4.2.11 on 2024-04-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_workout_created_at_remove_workout_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
