# Generated by Django 4.2.11 on 2024-04-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_goal_workoutprogram_aim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogramdetail',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Продолжительность (мин.)'),
        ),
    ]
