# Generated by Django 4.2.11 on 2024-04-04 23:35

from django.db import migrations, models
import django.db.models.deletion
import workout.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workouttype_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'тренировку', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'verbose_name': 'Тип тренировки', 'verbose_name_plural': 'Типы тренировок'},
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='workout_videos/', validators=[workout.validators.validate_video_extension], verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workout.workouttype', verbose_name='Тип тренировки'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('goal', models.CharField(choices=[('gain', 'Набор'), ('loss', 'Сушка'), ('maintain', 'Поддержание')], max_length=10, verbose_name='Цель')),
                ('workouts', models.ManyToManyField(related_name='programs', to='workout.workout', verbose_name='Тренировки')),
            ],
            options={
                'verbose_name': 'Программа тренировок',
                'verbose_name_plural': 'Программы тренировок',
                'unique_together': {('gender', 'goal')},
            },
        ),
    ]
