# Generated by Django 4.2.11 on 2024-04-14 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0003_alter_workoutprogramdetail_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workouttype',
            options={'ordering': ['title'], 'verbose_name': 'тип тренировки', 'verbose_name_plural': 'типы тренировок'},
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('completed_workouts', models.ManyToManyField(blank=True, related_name='completed_workouts', to='workout.workout', verbose_name='Выполненные тренировки')),
                ('current_workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.workout', verbose_name='Текущая тренировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workout_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.workouttype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'сессия пользователя',
                'verbose_name_plural': 'сессии пользователей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
