# Generated by Django 4.2.11 on 2024-04-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_workout_options_alter_workouttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'тренировка', 'verbose_name_plural': 'тренировки'},
        ),
        migrations.AlterModelOptions(
            name='workoutprogram',
            options={'verbose_name': 'программа тренировок', 'verbose_name_plural': 'программы тренировок'},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'verbose_name': 'тип тренировки', 'verbose_name_plural': 'типы тренировок'},
        ),
        migrations.AddField(
            model_name='workouttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='workout_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='workouts',
            field=models.ManyToManyField(related_name='programs', to='workout.workout', verbose_name='тренировки'),
        ),
    ]
