# Generated by Django 4.2.11 on 2024-04-14 00:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0004_alter_workouttype_options_usersession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSession',
            new_name='UserWorkoutSession',
        ),
    ]
