# Generated by Django 4.2.11 on 2024-04-06 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_workout_options_alter_workoutprogram_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutprogram',
            name='workouts',
        ),
        migrations.CreateModel(
            name='WorkoutProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('repetitions', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество повторений')),
                ('sets', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество подходов')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность (чч:мм:сс)')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout', verbose_name='Тренировка')),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_details', to='workout.workoutprogram', verbose_name='Программа тренировок')),
            ],
            options={
                'verbose_name': 'деталь программы тренировок',
                'verbose_name_plural': 'детали программы тренировок',
                'ordering': ['order'],
                'unique_together': {('workout_program', 'workout', 'order')},
            },
        ),
    ]
