# Generated by Django 4.2.11 on 2024-04-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_remove_workoutprogram_workouts_workoutprogramdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='workouts',
            field=models.ManyToManyField(related_name='programs', through='workout.WorkoutProgramDetail', to='workout.workout', verbose_name='Тренировки'),
        ),
    ]
