# Generated by Django 4.2.11 on 2024-04-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_workoutprogram_workouts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutprogramdetail',
            options={'ordering': ['order'], 'verbose_name': 'элемент программы тренировок', 'verbose_name_plural': 'элементы программы тренировок'},
        ),
    ]
