# Generated by Django 4.2.11 on 2024-04-06 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_workoutprogramdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogramdetail',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Продолжительность (мин.)'),
        ),
    ]
