# Generated by Django 4.2.11 on 2024-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_alter_workoutprogramdetail_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogramdetail',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность (мин.)'),
        ),
    ]
