# Generated by Django 4.2.11 on 2024-04-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.DateTimeField(auto_now_add=True, verbose_name='Время сна')),
                ('wake_time', models.DateTimeField(blank=True, null=True, verbose_name='Время пробуждения')),
                ('is_sleeping', models.BooleanField(default=True, verbose_name='Признак "лёг"')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сон',
                'verbose_name_plural': 'Сны',
                'ordering': ['-sleep_time'],
            },
        ),
    ]
