# Generated by Django 4.2.11 on 2024-04-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleep", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sleep",
            name="wake_time",
        ),
    ]
