# Generated by Django 4.2.11 on 2024-04-01 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('current_weight', models.PositiveIntegerField(verbose_name='Текущий вес (кг.)')),
                ('height', models.PositiveIntegerField(verbose_name='Рост (см.)')),
                ('year_of_birth', models.PositiveIntegerField(verbose_name='Год рождения')),
                ('goal', models.CharField(choices=[('gain', 'Набор'), ('loss', 'Сушка'), ('maintain', 'Поддержание')], max_length=10, verbose_name='Цель')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Сидячий образ жизни'), ('light', 'Тренировки 1-3 раза в неделю'), ('moderate', 'Тренировки 3-5 раз в неделю'), ('intensive', 'Тренировки 6-7 раз в неделю'), ('athlete', 'Тренировки каждый день чаще чем раз в день')], max_length=20, verbose_name='Активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
