# Generated by Django 4.2.11 on 2024-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='activity_level',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='goal',
            new_name='aim',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='year_of_birth',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_weight',
            field=models.FloatField(verbose_name='Текущий вес (кг.)'),
        ),
    ]
